# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'MiiboxApp' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MiiboxApp
    pod 'Kanna'
    pod 'Alamofire'
    pod 'SDWebImage'
    pod 'JGProgressHUD'
    pod 'MJRefresh'
    pod 'Font-Awesome-Swift', '~> 1.4.7'
  target 'MiiboxAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MiiboxAppUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
